DROP DATABASE IF EXISTS test;
CREATE USER IF NOT EXISTS "${MY_SQL_USER}"@'%' IDENTIFIED BY '${MY_SQL_PASSWORD}';
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};
GRANT ALL PRIVILEGES ON *.* TO "${MY_SQL_USER}"@'%';
FLUSH PRIVILEGES;
